### PR TITLE
Get rid of typescript

### LINKED ISSUE #12: fix typescript warnings
this is for sure the thing that i really dislike on typescript, but we choose this lane so we should drive it to the end :)
- [ ] missing slug module definition
- [ ] missing btoa/atob mod definition
- [ ] missing remarkable mod definition
- [ ] fix array function call on union types `(string|string[])`
- [ ] duplicate promise def, because of double reference in nodeify lib
- [ ] nodeify signature fix

I know, it is a tedious task but lets fix these, or move away from typescript

### PR DESCRIPTION
**Pull request by mechanoid**
Because of the pretty bad handling of 3rd Party Libraries, we decided to move away from typescript. In a first step we just move to plain es6. In a later step we will maybe try to enhance the src with facebook flow, which seems to be better in handling 3rd party libs.

resolves #12

### CODE REVIEW

**Comment by arty-name** [comment]
Wouldn’t it be nice to squash first two commits and thus get the continuity of code between TS and ES6?

**Comment by mechanoid** [comment]
i think that would have been cleaner yes, but otherwise it stated the history, that src is completely echanged.

**Comment by arty-name** [comment]
Weird, I thought there would be lots of similarities between TS and ES6 code.

**Comment by mechanoid** [comment]
in general it is, but if it comes down to the details there are some differences. But hard to nail them down, or better said, maybe the differences are now smaller, because TS tries to bring them closer i guess. The import statements i changed worked in this syntax, but not it is not exactly like es6 final for external dependencies. Therefore i fixed them to get the babel-only build working

**Pull request merged**
